# Generated by Django 4.2.4 on 2023-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_collected_customuser_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='collected',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='donated',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
        ),
    ]
